// Run with PLAYWRIGHT_MODULE pointing to the installed Playwright module.
// PLAYWRIGHT_CHANNEL picks an installed browser (e.g. msedge on Windows);
// leave it unset to use Playwright's bundled Chromium (e.g. in a cloud sandbox).
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
  const browser = await chromium.launch({headless:true, channel:process.env.PLAYWRIGHT_CHANNEL || undefined});
  const page = await browser.newPage({viewport:{width:1440,height:1000}, deviceScaleFactor:1});
  const screenshot = (name) => page.screenshot({path:path.join(os.tmpdir(),name), fullPage:true, animations:'disabled'});
  page.setDefaultTimeout(10000);
  const errors = [];
  let unexpectedSubmissions = 0;
  await page.route('**/*', async route => {
    if(route.request().method() === 'POST') {
      unexpectedSubmissions++;
      await route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({detail:'QA: unexpected early submission'})});
    } else await route.continue();
  });
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto(process.env.QA_URL || 'http://localhost:3000');
  await page.getByRole('button', {name:'Start your project'}).waitFor();
  const dir = os.tmpdir();
  await screenshot('enerzen-desktop.png');
  await page.getByRole('button', {name:'Start your project'}).click();
  await page.getByRole('heading', {name:'What are we creating?'}).waitFor();
  await screenshot('enerzen-paths.png');
  await page.getByRole('button').filter({hasText:'Room for a community.'}).click();
  await page.getByRole('heading', {name:'Development',exact:true}).waitFor();
  await page.getByLabel('Lot width').fill('45');
  assert.ok((await page.getByLabel('Live project brief').filter({visible:true}).innerText()).includes('2,250 m²'));
  await page.getByLabel('Lot width').press('Enter');
  assert.equal(unexpectedSubmissions,0,'Enter must not submit an incomplete wizard');
  await page.getByRole('button',{name:'Continue',exact:false}).click();
  await page.getByRole('heading',{name:'Planning',exact:true}).waitFor();
  await page.getByRole('heading',{name:'Pickering data library'}).waitFor({timeout:20000});
  await screenshot('enerzen-planning.png');
  await page.getByRole('button',{name:'← Back',exact:true}).click();
  console.log('Back navigation');
  assert.equal(await page.getByLabel('Lot width').inputValue(),'45');
  await page.getByLabel('Lot width').fill('1');
  console.log('Invalid width');
  await page.getByRole('button',{name:'Continue',exact:false}).click();
  assert.equal(await page.getByRole('heading',{name:'Development',exact:true}).count(),1);
  await page.getByLabel('Lot width').fill('45');
  console.log('Valid width');
  await page.getByRole('button',{name:'Continue',exact:false}).click();
  await page.getByRole('button',{name:'Continue',exact:false}).click();
  await page.getByRole('heading',{name:'Typology',exact:true}).waitFor();
  console.log('Typology');
  assert.ok(await page.getByRole('checkbox').count()>0);
  await page.getByRole('button',{name:'Continue',exact:false}).click();
  await page.getByRole('button',{name:'Review brief',exact:false}).click();
  await page.getByRole('heading',{name:'Review',exact:true}).waitFor();
  await page.getByRole('button',{name:'Change path',exact:false}).click();
  await page.getByRole('button').filter({hasText:'A place to call home.'}).click();
  await page.getByRole('heading',{name:'Brief',exact:true}).waitFor();
  for(let i=0;i<3;i++) await page.getByRole('button',{name:'Continue',exact:false}).click();
  await page.getByRole('heading',{name:'Systems',exact:true}).waitFor();
  await page.getByRole('button',{name:'Set priorities',exact:false}).click();
  await page.getByRole('heading',{name:'Priorities',exact:true}).waitFor();
  await screenshot('enerzen-unit.png');
  await page.setViewportSize({width:390,height:844});
  await screenshot('enerzen-mobile-workflow.png');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile overflow');
  await page.getByRole('button',{name:'EnerZen home',exact:true}).click();
  await screenshot('enerzen-mobile.png');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'landing overflow');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.ambient i').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  assert.deepEqual(errors,[]);
  assert.equal(unexpectedSubmissions,0,'Navigation must not submit before the final action');
  await browser.close();
  console.log('PASS: both paths, Pickering data, back navigation, validation, mobile overflow, reduced motion; screenshots in '+dir);
})().catch(e=>{console.error(e);process.exit(1)});
